### ISSUE TITLE
map data file little error

### ISSUE THREAD

**Issue by JHXSMatthew** [SoullessWaffle/eve-map-json#1]
universe_pretty.json
line 29425
should be system name 6E-578 instead of 0

**Comment by mickdekkers** [comment]
Hey, thanks for letting me know.
I rewrote the generation script and this issue is now fixed.

You can find the new `universe-pretty.json` file in the [dist folder](https://github.com/SoullessWaffle/eve-map-json/tree/master/dist)
It's also good to know that I changed the names of the `nodes` and `edges` keys to `solarSystems` and `jumps`.
